/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gabriel_querbes_final_05082016;

import gabriel_querbes_final_05082016.it.gmu.edu.model.Address;
import gabriel_querbes_final_05082016.it.gmu.edu.model.Customer;
import gabriel_querbes_final_05082016.it.gmu.edu.model.MyBooksComboBoxModel;
import gabriel_querbes_final_05082016.it.gmu.edu.model.MyComboBoxModel;
import gabriel_querbes_final_05082016.it.gmu.edu.model.MyTableModel;
import gabriel_querbes_final_05082016.it.gmu.edu.model.Order;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author gabrielquerbes
 */
public class Bookstore extends javax.swing.JFrame implements ActionListener {
    //data structure
    LinkedList<Customer> myCustomers = new LinkedList <>();
    Customer currentCustomer;
    int currentRow;
    
    /**
     * Creates new form Bookstore
     */
    public Bookstore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        shippingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtShipFirstName = new javax.swing.JTextField();
        txtShipLastName = new javax.swing.JTextField();
        txtShipStreet = new javax.swing.JTextField();
        txtShipCity = new javax.swing.JTextField();
        txtShipZip = new javax.swing.JTextField();
        cmbxShipState = new javax.swing.JComboBox<>();
        orderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rdbtnCredit = new javax.swing.JRadioButton();
        rdbtnDebit = new javax.swing.JRadioButton();
        cmbxProduct = new javax.swing.JComboBox<>();
        spnrQuantity = new javax.swing.JSpinner();
        txtTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAccountNumber = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        shippingPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBillStreet = new javax.swing.JTextField();
        txtBillCity = new javax.swing.JTextField();
        txtBillZip = new javax.swing.JTextField();
        cmbxBillState = new javax.swing.JComboBox<>();
        chkbxSameAsShip = new javax.swing.JCheckBox();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setEnabled(false);

        jTable1.setModel(new MyTableModel());
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSplitPane1.setBottomComponent(jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shipping Address");

        jLabel4.setText("First Name");

        jLabel5.setText("Last Name");

        jLabel6.setText("Street Address");

        jLabel7.setText("City");

        jLabel8.setText("State");

        jLabel9.setText("Zip");

        txtShipFirstName.setText("gadsfaf");

        txtShipLastName.setText("sdfsd");

        txtShipStreet.setText("sdfsadfs");

        txtShipCity.setText("sdfasdf");

        txtShipZip.setText("11111");

        cmbxShipState.setModel(new MyComboBoxModel());

        javax.swing.GroupLayout shippingPanelLayout = new javax.swing.GroupLayout(shippingPanel);
        shippingPanel.setLayout(shippingPanelLayout);
        shippingPanelLayout.setHorizontalGroup(
            shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(shippingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtShipFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shippingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtShipStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shippingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtShipLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shippingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtShipCity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shippingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(cmbxShipState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(shippingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtShipZip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        shippingPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        shippingPanelLayout.setVerticalGroup(
            shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtShipFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShipLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtShipStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtShipCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxShipState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtShipZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shippingPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Order Detail");

        jLabel3.setText("Product ");

        jLabel11.setText("Quantity");

        jLabel12.setText("Payment Type");

        jLabel13.setText("Total Cost");

        buttonGroup1.add(rdbtnCredit);
        rdbtnCredit.setSelected(true);
        rdbtnCredit.setText("Credit");
        rdbtnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCreditActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtnDebit);
        rdbtnDebit.setText("Debit");

        cmbxProduct.setModel(new MyBooksComboBoxModel());

        txtTotal.setEditable(false);

        jLabel14.setText("Account Number");

        txtAccountNumber.setText("1111111");
        txtAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(rdbtnCredit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnDebit)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(cmbxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnrQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spnrQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnCredit)
                    .addComponent(rdbtnDebit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Billing Address");

        jLabel19.setText("Street Address");

        jLabel20.setText("City");

        jLabel21.setText("State");

        jLabel22.setText("Zip");

        cmbxBillState.setModel(new MyComboBoxModel());

        chkbxSameAsShip.setText("Same as Shipping");
        chkbxSameAsShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxSameAsShipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shippingPanel1Layout = new javax.swing.GroupLayout(shippingPanel1);
        shippingPanel1.setLayout(shippingPanel1Layout);
        shippingPanel1Layout.setHorizontalGroup(
            shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(shippingPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBillStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shippingPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBillZip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shippingPanel1Layout.createSequentialGroup()
                        .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(shippingPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cmbxBillState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtBillCity, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shippingPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkbxSameAsShip)
                        .addGap(68, 68, 68)))
                .addContainerGap())
        );
        shippingPanel1Layout.setVerticalGroup(
            shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(chkbxSameAsShip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtBillStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBillCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmbxBillState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shippingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtBillZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shippingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(shippingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shippingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shippingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel)
                    .addComponent(btnUpdate))
                .addGap(35, 35, 35))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnCreditActionPerformed

    private void chkbxSameAsShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxSameAsShipActionPerformed
        // TODO add your handling code here:
        if (chkbxSameAsShip.isSelected()){
            txtBillStreet.setText(txtShipStreet.getText());
            txtBillCity.setText(txtShipCity.getText());
            cmbxBillState.setSelectedItem(cmbxShipState.getSelectedItem());
            txtBillZip.setText(txtShipZip.getText());
        }
        else{
            clearBilling();
        }
        
      
    }//GEN-LAST:event_chkbxSameAsShipActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

      private class RowListener implements ListSelectionListener {
        public void valueChanged(ListSelectionEvent event) {
            System.out.print("ROW SELECTION EVENT. ");
            if (event.getValueIsAdjusting()) {
                return;
            }
            
            
        }
    }

   
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //check if item is selected
       
        
        boolean valid = true;
        String errorMessage = "";
        Customer aCustomer = new Customer();
        Order aOrder = new Order();
        Address shippingAddress = new Address();
        Address billingAddress = new Address();
        
        //validate fields
        
        //Customer
        if(!aCustomer.setFirstName(txtShipFirstName.getText())){
            errorMessage += "Invalid First Name";
            valid = false;
        }
        if(!aCustomer.setLastName(txtShipLastName.getText())){
            errorMessage += "\nInvalid Last Name";
            valid = false;
        }
        
         
        
        //Shipping
        if(!shippingAddress.setStreetAddress(txtShipStreet.getText())){
            errorMessage += "\nInvalid Shipping Steet Address";
            valid = false;
        }
        if(!shippingAddress.setCity(txtShipCity.getText())){
            errorMessage += "\nInvalid Shipping City";
            valid = false;
        }
        if(!shippingAddress.setState((String) cmbxShipState.getSelectedItem())){
            errorMessage += "\nInvalid Shipping Sate";
            valid = false;
        }
        if(!shippingAddress.setZipCode(txtShipZip.getText())){
            errorMessage += "\nInvalid Shipping Zip Code, Must be 5 digits";
            valid = false;
        }
        //billing
        if(!billingAddress.setStreetAddress(txtBillStreet.getText())){
            errorMessage += "\nInvalid Billing Steet Address";
            valid = false;
        }
        if(!billingAddress.setCity(txtBillCity.getText())){
            errorMessage += "\nInvalid Billing City";
            valid = false;
        }
        if(!billingAddress.setState((String) cmbxBillState.getSelectedItem())){
            errorMessage += "\nInvalid Billing State";
            valid = false;
        }
        if(!billingAddress.setZipCode(txtBillZip.getText())){
            errorMessage += "\nInvalid Billing Zip Code, Must be 5 digits";
            valid = false;
        }
        
        
        //order
        if((String)cmbxProduct.getSelectedItem() == ""){
            errorMessage += "\nInvalid Product Selected";
            valid = false;
        }else{aOrder.setProduct((String) cmbxProduct.getSelectedItem());}
        
        if(rdbtnCredit.isSelected()){
            aOrder.setPaymentType("Credit");
        }else{
            aOrder.setPaymentType("Debit");
        }
        
        if((int)spnrQuantity.getValue() == 0){
            errorMessage += "\nQuantity Cannot be 0";
            valid = false;
        }else{aOrder.setQuantity((int)spnrQuantity.getValue());}
        
        if(!aOrder.setAccountNumber(txtAccountNumber.getText())){
            errorMessage += "\nAccount Number MUST be 7 digits";
            valid = false;
        }
        
        
        
        if(!valid){
            JOptionPane.showMessageDialog(null, "CORRECT ERROR(s):\n" + errorMessage);
            System.out.println("fail");
           
        }
        else{
            //add data
            aCustomer.setBillingAddresss(billingAddress);
            aCustomer.setShippingAddress(shippingAddress);
            aCustomer.setOrders(aOrder);
            //add customer to local linked list
            myCustomers.add(aCustomer);
            //add customer to table
            addCustomerTolist(aCustomer);
           
            JOptionPane.showMessageDialog(null, "Order Created");
            System.out.println("success");
            
            //clear screen
            clearAll();
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    
   

    


    public void addCustomerTolist(Customer aCustomer){
         
        MyTableModel model = (MyTableModel) jTable1.getModel();
        model.addData(aCustomer);
      
    }
    
    public void updateCustomerOnList(Customer aCustomer){
        MyTableModel model = (MyTableModel) jTable1.getModel();
        model.editData(aCustomer,currentRow);
        
    }
    
    private void txtAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNumberActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        MyTableModel model = (MyTableModel) jTable1.getModel();
        int row = jTable1.rowAtPoint(evt.getPoint());
        Customer aCustomer = myCustomers.get(row);
        // populate table with data
        //shipping
        txtShipFirstName.setText(aCustomer.getFirstName());
        txtShipLastName.setText(aCustomer.getLastName());
        txtShipStreet.setText(aCustomer.getShippingAddress().getStreetAddress());
        txtShipCity.setText(aCustomer.getShippingAddress().getCity());
        txtShipZip.setText(aCustomer.getShippingAddress().getZipCode());
        cmbxShipState.setSelectedItem(aCustomer.getShippingAddress().getState());
        
        //billing
        txtBillStreet.setText(aCustomer.getBillingAddresss().getStreetAddress());
        txtBillCity.setText(aCustomer.getBillingAddresss().getCity());
        txtBillZip.setText(aCustomer.getBillingAddresss().getZipCode());
        cmbxBillState.setSelectedItem(aCustomer.getBillingAddresss().getState());
        
        //order
        spnrQuantity.setValue(aCustomer.getOrders().getQuantity());
        if(aCustomer.getOrders().getPaymentType().equals("Credit")){
            rdbtnCredit.setSelected(true);
        }else{
            rdbtnDebit.setSelected(true);
        }
        txtTotal.setText(Double.toString( aCustomer.getOrders().getQuantity() * 50.00));
        txtAccountNumber.setText(aCustomer.getOrders().getAccountNumber());
        cmbxProduct.setSelectedItem(aCustomer.getOrders().getProduct());
        
        //hide the submit button
        btnSubmit.setEnabled(false);
        //show update button
        btnUpdate.setEnabled(true);
        
        
        //set current customer for edit
        currentCustomer = aCustomer;
        currentRow = row;
        
        //reset screen
//        clearAll();
//        btnSubmit.enable(true);
//        btnUpdate.enable(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        clearAll();
        btnSubmit.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      
        Customer aCustomer = currentCustomer;
        Address shippingAddress = aCustomer.getShippingAddress();
        Address billingAddress = aCustomer.getBillingAddresss();
        Order aOrder = aCustomer.getOrders();
        
        // TODO add your handling code here:
          boolean valid = true;
         String errorMessage = "";
        //validate fields

        if(!aCustomer.setFirstName(txtShipFirstName.getText())){
            errorMessage += "Invalid First Name";
            valid = false;
        }
        if(!aCustomer.setLastName(txtShipLastName.getText())){
            errorMessage += "\nInvalid Last Name";
            valid = false;
        }
        
        //Shipping
        if(!shippingAddress.setStreetAddress(txtShipStreet.getText())){
            errorMessage += "\nInvalid Shipping Steet Address";
            valid = false;
        }
        if(!shippingAddress.setCity(txtShipCity.getText())){
            errorMessage += "\nInvalid Shipping City";
            valid = false;
        }
        if(!shippingAddress.setState((String) cmbxShipState.getSelectedItem())){
            errorMessage += "\nInvalid Shipping Sate";
            valid = false;
        }
        if(!shippingAddress.setZipCode(txtShipZip.getText())){
            errorMessage += "\nInvalid Shipping Zip Code, Must be 5 digits";
            valid = false;
        }
        //billing
        if(!billingAddress.setStreetAddress(txtBillStreet.getText())){
            errorMessage += "\nInvalid Billing Steet Address";
            valid = false;
        }
        if(!billingAddress.setCity(txtBillCity.getText())){
            errorMessage += "\nInvalid Billing City";
            valid = false;
        }
        if(!billingAddress.setState((String) cmbxBillState.getSelectedItem())){
            errorMessage += "\nInvalid Billing State";
            valid = false;
        }
        if(!billingAddress.setZipCode(txtBillZip.getText())){
            errorMessage += "\nInvalid Billing Zip Code, Must be 5 digits";
            valid = false;
        }
        
        //order
        if((String)cmbxProduct.getSelectedItem() == ""){
            errorMessage += "\nInvalid Product Selected";
            valid = false;
        }else{aOrder.setProduct((String) cmbxProduct.getSelectedItem());}
        
        if(rdbtnCredit.isSelected()){
            aOrder.setPaymentType("Credit");
        }else{
            aOrder.setPaymentType("Debit");
        }
        
        if((int)spnrQuantity.getValue() == 0){
            errorMessage += "\nQuantity Cannot be 0";
            valid = false;
        }else{aOrder.setQuantity((int)spnrQuantity.getValue());}
        
        if(!aOrder.setAccountNumber(txtAccountNumber.getText())){
            errorMessage += "\nAccount Number MUST be 7 digits";
            valid = false;
        }
        

        if(!valid){
            JOptionPane.showMessageDialog(null, "CORRECT ERROR(s):\n" + errorMessage);
            System.out.println("fail");
           
        }
        
        
        //update table
        updateCustomerOnList(aCustomer);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look andfeel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookstore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookstore().setVisible(true);
            }
        });
        
    }

    public void clearAll(){
        clearShipping();
        clearBilling();
        clearOrder();
    }
    public void clearShipping(){
        txtShipFirstName.setText("");
        txtShipLastName.setText("");
        txtShipStreet.setText("");
        txtShipCity.setText("");
        txtShipZip.setText("");
        cmbxShipState.setSelectedItem("");
        
    }
    
    public void clearBilling(){
        txtBillStreet.setText("");
        txtBillCity.setText("");
        txtBillZip.setText("");
        cmbxBillState.setSelectedItem("");
        
    }
    
    public void clearOrder(){
        spnrQuantity.setValue(0);
        rdbtnCredit.setSelected(false);
        rdbtnDebit.setSelected(false);
        txtTotal.setText("");
        txtAccountNumber.setText("");
        cmbxProduct.setSelectedItem("");
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkbxSameAsShip;
    private javax.swing.JComboBox<String> cmbxBillState;
    private javax.swing.JComboBox<String> cmbxProduct;
    private javax.swing.JComboBox<String> cmbxShipState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JRadioButton rdbtnCredit;
    private javax.swing.JRadioButton rdbtnDebit;
    private javax.swing.JPanel shippingPanel;
    private javax.swing.JPanel shippingPanel1;
    private javax.swing.JSpinner spnrQuantity;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBillCity;
    private javax.swing.JTextField txtBillStreet;
    private javax.swing.JTextField txtBillZip;
    private javax.swing.JTextField txtShipCity;
    private javax.swing.JTextField txtShipFirstName;
    private javax.swing.JTextField txtShipLastName;
    private javax.swing.JTextField txtShipStreet;
    private javax.swing.JTextField txtShipZip;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
